# Site settings
title: Sriman Darbha
email: sriman1988@yahoo.com
description: "This is my personal web-blog, you can fork me on github, tweet me on twitter and even mail me on the email address on the left :)"
baseurl: ""
url: "http://srimandarbha.com"
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

image:
          background: linux.is.sexy..png
# Build settings
markdown: kramdown
permalink: pretty
