# Site settings
title: Sriman Darbha
email: sriman1988@yahoo.com
description: "Sriman Darbha's web-blog."
baseurl: "srimandarbha.herokuapp.com"
url: "http://srimandarbha.com"
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

# Build settings
markdown: kramdown
permalink: pretty
