# Site settings
title: This is my personal blog. You can fork me on gihub tweet me on twitter or mail me to the below url.
email: sriman1988@yahoo.com
description: "Sriman Darbha's web-blog."
baseurl: ""
url: "http://srimandarbha.com"
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

# Build settings
markdown: kramdown
permalink: pretty
