# Site settings
title: srimandarbha
email: sriman1988@yahoo.com
description: "Sriman Darbha's web-blog."
baseurl: ""
url: "http://srimandarbha.com"
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

# Build settings
markdown: kramdown
permalink: pretty
